# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qianqian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名字')),
                ('singer', models.CharField(max_length=255, verbose_name='歌手')),
                ('album', models.CharField(max_length=255, verbose_name='专辑')),
                ('pub_date', models.CharField(max_length=255, verbose_name='发行时间')),
                ('pub_company', models.CharField(max_length=255, verbose_name='发布公司')),
                ('like_num', models.CharField(max_length=255, verbose_name='喜欢数量')),
                ('comment_num', models.CharField(max_length=255, verbose_name='评论数量')),
                ('share_num', models.CharField(max_length=255, verbose_name='分享数量')),
                ('lrc', models.TextField(verbose_name='歌词')),
            ],
            options={
                'verbose_name': '千千音乐',
                'verbose_name_plural': '千千音乐',
                'db_table': 'music',
            },
        ),
    ]
